summersite/summersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('homepage/', include('homepage.urls')),
    path("users/", include("django.contrib.auth.urls")),
    path('users/', include('user.urls')),
    path('teachings/', include('teachings.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

summersite/teachings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ViewMyCourses.as_view(), name='my_teaching_courses'),
    # path('<int:course_id>/summary', views.course_summary, name='course_summary'),
    path('<int:course_id>/course_detail',
         views.CourseDetail.as_view(), name='course_detail'),
    path('<int:course_id>/<int:lecture_id>/lecture_detail',
         views.LectureDetail.as_view(), name='lecture_detail'),
    path('create_lecture/<int:course_id>',
         views.CreateLectureView.as_view(), name='create_lecture'),
    path('update_lecture/<int:pk>',
         views.UpdateLectureView.as_view(), name='update_lecture'),
    path('delete_lecture/<int:pk>',
         views.DeleteLectureView.as_view(), name='delete_lecture'),
    path('create_note/<int:lecture_id>',
         views.CreateNoteView.as_view(), name='create_note'),
    path('update_note/<int:pk>',
         views.UpdateNoteView.as_view(), name='update_note'),
    path('delete_note/<int:pk>',
         views.DeleteNoteView.as_view(), name='delete_note'),
    path('create_video/<int:lecture_id>',
         views.CreateVideoView.as_view(), name='create_video'),
    path('update_video/<int:pk>',
         views.UpdateVideoView.as_view(), name='update_video'),
    path('delete_video/<int:pk>',
         views.DeleteVideoView.as_view(), name='delete_video'),
]

summersite/user/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    
    path('signup/', SignUpView.as_view(), name='signup'),
    
    
]

summersite/courses/models.py
from django.db import models
from user.models import MyUser
from django.utils.timezone import datetime
from django.urls import reverse


class Term(models.Model):

    SEASON_CHOICES = [
        ('SPRING', 'Spring'),
        ('SUMMER_1', 'Summer_1'),
        ('SUMMER_2', 'Summer_2'),
        ('FALL', 'Fall'),
    ]
    year = models.CharField(
        max_length=4,
        help_text="Year of the term, e.g. 2023",
        blank=False,
        verbose_name='Year'
    )
    season = models.CharField(
        max_length=8,
        choices=SEASON_CHOICES,
        help_text="Season of the term, e.g. Fall.",
        blank=False,
        verbose_name='Season'
    )
    start_date = models.DateField(
        help_text="Start date of the term.",
        verbose_name='Start Date'
    )
    end_date = models.DateField(
        help_text="End date of the term.",
        verbose_name='End Date'
    )

    def __str__(self):
        return self.year + " " + self.season.capitalize()


class Course(models.Model):

    SUBJECT_CHOICES = [
        ('APBI', 'APBI'),
        ('APSC', 'APSC'),
        ('BIOL', 'BIOL'),
        ('CHEM', 'CHEM'),
        ('COMM', 'COMM'),
        ('COMR', 'COMR'),
        ('CPEN', 'CPEN'),
        ('CPSC', 'CPSC'),
        ('DCSI', 'DCSI'),
        ('ECON', 'ECON'),
        ('ELEC', 'ELEC'),
        ('EOSC', 'EOSC'),
        ('MATH', 'MATH'),
        ('MFRE', 'MFRE'),
        ('PHIL', 'PHIL'),
        ('PHYS', 'PHYS'),
        ('PSYC', 'PSYC'),
        ('SCIE', 'SCIE'),
        ('STAT', 'STAT'),
        ('VANT', 'VANT'),
        ('WRDS', 'WRDS'),
    ]

    subject = models.CharField(
        max_length=4,
        choices=SUBJECT_CHOICES,
        help_text="Subject code, e.g. ECON.",
        blank=False,
        verbose_name='Subject'
    )
    course_number = models.CharField(
        max_length=3,
        help_text="3-digits course number, e.g. 101.",
        blank=False,
        verbose_name='Course Number'
    )
    section = models.CharField(
        max_length=20,
        help_text="Section number, e.g. 202 or professor name. <strong>Leave it blank</strong> if there is only one section.",
        blank=True,
        verbose_name='Section'
    )
    term = models.ForeignKey(
        Term,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Term'
    )
    instructor = models.ForeignKey(
        MyUser,
        models.SET_NULL,
        limit_choices_to={'is_tutor': True},
        blank=True,
        null=True,
        verbose_name='Instructor'
    )
    # slug = models.SlugField()

    def is_active(self) -> bool:
        return datetime.today().date() >= self.term.start_date and datetime.today().date() <= self.term.end_date

    def get_short_title(self):
        return self.subject + self.course_number + self.section

    def get_long_title(self):
        return self.subject + self.course_number + self.section + "---" + self.term.__str__()

    def __str__(self):
        return self.subject + self.course_number + " - " + self.section + self.term.__str__()


class Lecture(models.Model):
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        help_text="Select the course.",
        verbose_name='Course'
    )
    title = models.CharField(
        max_length=300,
        default='',
        help_text='Enter the title of the lecture, e.g. Math101 Lecture 1.',
        verbose_name='Title'
    )
    week = models.PositiveIntegerField(
        blank=False,
        help_text='Enter the week number.',
        verbose_name='Week No.'
    )
    syllabus = models.TextField(
        blank=True,
        help_text="A short syllabus of this lecture."
    )
    is_midterm = models.BooleanField(
        default=False,
        help_text="Is this a midterm review lecture?",
        verbose_name='Midterm Review?'
    )
    is_final = models.BooleanField(
        default=False,
        help_text="Is this a final review lecture?",
        verbose_name="Final Review?"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Create Time'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Update Time'
    )
    # slug = models.SlugField(
    #     default = "",
    #     null = True
    # )

    def get_short_title(self):
        return "Week" + str(self.week) + "---" + self.title

    def __str__(self):
        return str(self.course) + " Week" + str(self.week) + "---" + self.title

    def get_absolute_url(self):
        return reverse('lecture_detail', args=[str(self.course.id), str(self.id)])


class UploadNote(models.Model):
    lecture = models.ForeignKey(
        Lecture,
        verbose_name='Lecture corresponds to the notes',
        on_delete=models.CASCADE
    )
    title = models.CharField(
        max_length=100,
        verbose_name='Title of notes',
        help_text='e.g. Week 1 notes'
    )
    upload_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Upload time'
    )
    document = models.FileField(
        upload_to='notes/',
        verbose_name='Document to be uploaded'
    )

    def __str__(self):
        return self.title

    def get_short_title(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lecture_detail', args=[str(self.lecture.course.id), str(self.lecture.id)])


class UploadVideo(models.Model):
    lecture = models.ForeignKey(
        Lecture,
        verbose_name='Lecture corresponds to the video',
        on_delete=models.CASCADE
    )
    title = models.CharField(
        max_length=100,
        verbose_name='Title of video',
        help_text='e.g. Week 1 recording'
    )
    upload_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Upload time'
    )
    document = models.FileField(
        upload_to='video/',
        verbose_name='Video to be uploaded'
    )

    def __str__(self):
        return self.title

    def get_short_title(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lecture_detail', args=[str(self.lecture.course.id), str(self.lecture.id)])

summersite/teachings/models.py
from django.db import models

# Create your models here.

summersite/teachings/forms.py
from django import forms
from courses.models import Lecture, UploadNote, UploadVideo


class CreateLectureForm(forms.ModelForm):

    class Meta:
        model = Lecture
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateLectureForm, self).__init__(*args, **kwargs)
        self.fields['course'].disabled = True


class CreateNoteForm(forms.ModelForm):

    class Meta:
        model = UploadNote
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateNoteForm, self).__init__(*args, **kwargs)
        self.fields['lecture'].disabled = True


class CreateVideoForm(forms.ModelForm):

    class Meta:
        model = UploadVideo
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateVideoForm, self).__init__(*args, **kwargs)
        self.fields['lecture'].disabled = True

summersite/teachings/views.py
from typing import Any, Dict, Optional
from django.db import models
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from courses.models import Course, Lecture, UploadNote, UploadVideo
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import CreateLectureForm, CreateNoteForm, CreateVideoForm
from django.urls import reverse_lazy


# @login_required(login_url="/users/login/")
# def my_classes(request):
#     my_courses = Course.objects.filter(
#         instructor=request.user).order_by('subject', 'course_number')
#     return render(
#         request,
#         'my_classes.html',
#         {
#             'my_courses': my_courses,
#             'user': request.user,
#         }
#     )


# def course_summary(request, course_id):
#     this_course = get_object_or_404(Course, pk=course_id)
#     lectures = Lecture.objects.filter(
#         course=this_course).order_by('week', 'created_at')
#     return render(
#         request,
#         'single_class.html',
#         {
#             'course': this_course,
#             'lectures': lectures,
#         }
#     )


class ViewMyCourses(ListView):
    model = Course
    template_name = 'my_courses.html'

    def get_queryset(self) -> QuerySet[Any]:
        qs = super(ViewMyCourses, self).get_queryset()
        return qs.filter(instructor=self.request.user)


class CourseDetail(DetailView):
    model = Course
    template_name = 'course_detail.html'
    pk_url_kwarg = 'course_id'

    # def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
    #     return super().get_context_data(**kwargs)


class LectureDetail(DetailView):
    model = Lecture
    template_name = 'lecture_detail.html'
    pk_url_kwarg = 'lecture_id'

    # def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
    #     context = super(LectureDetail, self).get_context_data(**kwargs)


class CreateLectureView(CreateView):
    model = Lecture
    template_name = 'create_lecture.html'
    # fields = '__all__'
    form_class = CreateLectureForm

    def get_initial(self):
        return {'course': Course.objects.get(id=self.kwargs['course_id'])}

    # def form_valid(self, form):
    #     print(self.request)
    #     lecture = form.save(commit=False)
    #     lecture.course = Course.objects.all().filter(
    #         pk=self.kwargs['course_id'])
    #     return super(CreateLectureView, self).form_valid(form)


class UpdateLectureView(UpdateView):
    model = Lecture
    template_name = 'update_lecture.html'
    fields = ['title', 'week', 'syllabus', 'is_midterm', 'is_final']


class DeleteLectureView(DeleteView):
    model = Lecture
    template_name = 'delete_lecture.html'

    def get_success_url(self) -> str:
        return reverse_lazy('course_detail', kwargs={
            'course_id': self.object.course.id})


class CreateNoteView(CreateView):
    model = UploadNote
    template_name = 'create_document.html'
    form_class = CreateNoteForm

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["lecture_id"] = self.kwargs['lecture_id']
        return context

    def get_initial(self):
        return {'lecture': Lecture.objects.get(id=self.kwargs['lecture_id'])}


class UpdateNoteView(UpdateView):
    model = UploadNote
    template_name = 'update_document.html'
    fields = ['title', 'document']


class DeleteNoteView(DeleteView):
    model = UploadNote
    template_name = 'delete_document.html'

    def get_success_url(self) -> str:
        return reverse_lazy('lecture_detail', kwargs={
            'course_id': self.object.lecture.course.id,
            'lecture_id': self.object.lecture.id
        })


class CreateVideoView(CreateView):
    model = UploadVideo
    template_name = 'create_video.html'
    form_class = CreateVideoForm

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["lecture_id"] = self.kwargs['lecture_id']
        return context

    def get_initial(self):
        return {'lecture': Lecture.objects.get(id=self.kwargs['lecture_id'])}


class UpdateVideoView(UpdateView):
    model = UploadVideo
    template_name = 'update_video.html'
    fields = ['title', 'document']


class DeleteVideoView(DeleteView):
    model = UploadVideo
    template_name = 'delete_video.html'

    def get_success_url(self) -> str:
        return reverse_lazy('lecture_detail', kwargs={
            'course_id': self.object.lecture.course.id,
            'lecture_id': self.object.lecture.id
        })

summersite/teachings/templates/course_detail.html
{% extends 'base.html' %}
{% block title %}
Course Detail
{% endblock %}
{% block content %}

{% if course.instructor == user %}
<div class="container">
<h1>{{ course.get_long_title }}</h1>
</div>
<br>
<div class="container">
<h2>Course Information</h2>
<ul>
    <li>
        <strong>Term:</strong> {{ course.term }}
    </li>
    <li>
        <strong>Tutor:</strong> {{ course.instructor }}
    </li>
    <li>
        <strong>Is the course active?:</strong> {{ course.is_active }}
    </li>
</ul>
</div>
<br>
<div class="container">
    <h2>Create a New Lecture</h2> <br>
    <div class="container">
        <a href="{% url 'create_lecture' course.id %}">Create a new lecture</a>
    </div>
</div>
<br>
<div class="container">
<h2>View Exsiting Lectures</h2>
<ul>
    {% for lecture in course.lecture_set.all %}
    <li>
        <div class="container">
            <p> <strong>Week {{ lecture.week }}---{{ lecture.title }}</strong> <a href="{% url 'lecture_detail' course.id lecture.id %}">View/Edit/Delete Lecture</a></p>
            <ul>
                <li>
                    <strong>Syllabus:</strong> {{ lecture.syllabus }}
                </li>
                <li>
                    <strong>Notes: </strong>
                    {% if lecture.uploadnote_set.all %}
                    <ul>
                        {% for note in lecture.uploadnote_set.all %}
                            <li>
                                Download Notes: <a href="{{ note.document.url }}" download="{{ note.document.url }}">{{ note.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p>
                            You don't have any notes uploaded yet.
                        </p>
                    {% endif %}
                </li>
                <li>
                    <strong>Videos: </strong>
                    {% if lecture.uploadvideo_set.all %}
                    <ul>
                        {% for video in lecture.uploadvideo_set.all %}
                            <li>
                                <video width="300" height="240" controls>
                                    <source src="{{ video.document.url }}" type="video/mp4">
                                    Your browser does not support video tag.
                                </video>
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>
                        You don't have any videos uploaded yet.
                    </p>
                    {% endif %}
                </li>
            </ul>
        </div>
    </li>
    {% endfor %}
</ul>
</div>
{% else %}
<h2>You are not the instructor of this course</h2>
{% endif %}
<div class="container">
    <a href="{% url 'my_teaching_courses' %}">Back to my courses</a>
</div>
{% endblock %}

summersite/teachings/templates/create_document.html
{% extends 'base.html' %}
{% block title %}
Create Notes/Documents
{% endblock %}
{% block content %}

<h1>Create New Notes</h1>
<form action="{% url 'create_note' lecture_id %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

summersite/teachings/templates/create_lecture.html
{% extends 'base.html' %}
{% block title %}
Create Lecture
{% endblock %}
{% block content %}

<h1>Create a New Lecture</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

summersite/teachings/templates/create_video.html
{% extends 'base.html' %}
{% block title %}
Create Video
{% endblock %}
{% block content %}

<h1>Create New Video</h1>
<form action="{% url 'create_video' lecture_id %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

summersite/teachings/templates/delete_document.html
{% extends 'base.html' %}
{% block title %}
Delete Notes
{% endblock %}
{% block content %}

<h1>Delete Notes</h1>
<br>
<h3>Delete: {{ object.get_short_title }}</h3>
<form method="post">
    {% csrf_token %}
    <strong>Are you sure?</strong>
    <br>
    <input type="submit" value="Delete">
</form>

{% endblock %}

summersite/teachings/templates/delete_lecture.html
{% extends 'base.html' %}
{% block title %}
Delete Lecture
{% endblock %}
{% block content %}

<h1>Delete Lecture</h1>
<br>
<h3>Delete: {{ lecture.get_short_title }}</h3>
<form method="post">
    {% csrf_token %}
    <strong>Are you sure?</strong>
    <br>
    <input type="submit" value="Delete">
</form>

{% endblock %}

summersite/teachings/templates/delete_video.html
{% extends 'base.html' %}
{% block title %}
Delete Video
{% endblock %}
{% block content %}

<h1>Delete Video</h1>
<br>
<h3>Delete: {{ object.get_short_title }}</h3>
<form method="post">
    {% csrf_token %}
    <strong>Are you sure?</strong>
    <br>
    <input type="submit" value="Delete">
</form>

{% endblock %}

summersite/teachings/templates/lecture_detail.html
{% extends 'base.html' %}
{% block title %}
Lecture Detail
{% endblock %}
{% block content %}

{% if lecture.course.instructor == user %}
<div class="container">
    <h2>Lecture Information</h2>
    <ul>
        <li>
            <strong>Course:</strong> {{ lecture.course.get_short_title }}
        </li>
        <li>
            <strong>Week No.:</strong> {{ lecture.week }}
        </li>
        <li>
            <strong>Title:</strong> {{ lecture.title }}
        </li>
        <li>
            <strong>Syllabus:</strong> <br>
            <p>{{ lecture.syllabus }}</p>
        </li>
        <li>
            <strong>Is this a midterm review lecture:</strong> <br>
            <p>{{ lecture.is_midterm }}</p>
        </li>
        <li>
            <strong>Is this a final review lecture:</strong> <br>
            <p>{{ lecture.is_final }}</p>
        </li>
    </ul>
    <p>
        <a href="{% url 'update_lecture' lecture.id %}">Edit Lecture</a> | <a href="{% url 'delete_lecture' lecture.id %}">Delete Lecture</a>
    </p>
</div>
<br>
<div class="container">
    <h2>Lecture Notes</h2>
    {% if lecture.uploadnote_set.all %}
    <ul>
        {% for note in lecture.uploadnote_set.all %}
            <li>
                Download <a href="{{ note.document.url }}" download="{{ note.document.url }}">{{ note.title }}</a> | 
                <a href="{% url 'update_note' note.id %}">Edit Notes</a> | 
                <a href="{% url 'delete_note' note.id %}">Delete Notes</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>
        You don't have any note uploaded yet.
    </p>
    {% endif %}
    <p>
        <a href="{% url 'create_note' lecture.id %}">Upload New Notes</a>
    </p>
</div>
<br>
<div class="container">
    <h2>Video Recordings of Lecture</h2>
    {% if lecture.uploadvideo_set.all %}
    <ul>
        {% for video in lecture.uploadvideo_set.all %}
        <li>
            <strong>{{ video.title }}</strong> | 
            <a href="{% url 'update_video' video.id %}">Edit Video</a> | 
            <a href="{% url 'delete_video' video.id %}">Delete Video</a>
            <div class="video-container">
                <video width="300" height="240" controls>
                    <source src="{{ video.document.url }}" type="video/mp4">
                    Your browser does not support video tag.
                </video>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>
        You don't have any video uploaded yet.
    </p>
    {% endif %}
    <p>
        <a href="{% url 'create_video' lecture.id %}">Upload New Videos</a>
    </p> 
</div>
{% else %}
<div class="container">
    <h2>You are not the instructor of this course!</h2>
</div>
{% endif %}
<div class="container">
    <a href="{% url 'course_detail' lecture.course.id %}">Back to the course</a>
</div>
{% endblock %}

summersite/teachings/templates/my_classes.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome back, {{ user.username }}</h1>
<ul>
    {% if user.is_tutor %}
    <h2>All courses taught by me:</h2>
    <ul>
        {% for course in my_courses %}
            <li>
                <a href="{% url 'course_summary' course.id %}">{{ course.get_title }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You are not an instructor!</p>
    {% endif %}
</ul>

{% endblock %}

summersite/teachings/templates/my_courses.html
{% extends 'base.html' %}
{% block title %}
My Courses
{% endblock %}

{% block content %}

<h1>Welcome back, {{ user.username }}</h1>
<ul>
    {% if user.is_tutor %}
    <h2>All courses taught by me:</h2>
    <ul>
        {% for course in object_list %}
        <li>
            <a href="{% url 'course_detail' course.id %}">{{ course.get_short_title }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You are not an instructor!</p>
    {% endif %}
</ul>

{% endblock %}

summersite/teachings/templates/single_class.html
{% extends 'base.html' %}

{% block content %}

{% if course.instructor == user %}
<h1>{{ course.get_title }}</h1>
<ul>
    {% for lecture in lectures %}
        <li>
            <a href="#">{{ lecture.title }}</a>
            <ul>
                <li>
                    <strong>Syllabus</strong>
                    <p>{{ lecture.syllabus }}</p>
                </li>
                <li>
                    <strong>Notes</strong> <br>
                    {% for note in lecture.uploadnote_set.all %}
                        <a href="{{ note.document.url }}" download="{{ note.document.url }}">Download {{ note.document }}</a> <br>
                    {% endfor %}
                </li>
                <li>
                    <strong>Videos</strong> <br>
                    {% for video in lecture.uploadvideo_set.all %}
                        <video width="300" height="240" controls>
                            <source src="{{ video.document.url }}" type="video/mp4">
                            Your browser does not support video tag.
                        </video>
                    {% endfor %}
                </li>
            </ul>
        </li>
    {% endfor %}
</ul>
<br>
<br>
<a href="#">Create a new lecture</a>
{% else %}
<h2>You are not the instructor of this course</h2>
{% endif %}
{% endblock %}

summersite/teachings/templates/update_document.html
{% extends 'base.html' %}
{% block title %}
Update Notes/Documents
{% endblock %}
{% block content %}

<h1>Update Notes</h1>
<form action="{% url 'update_note' uploadnote.pk %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

summersite/teachings/templates/update_lecture.html
{% extends 'base.html' %}
{% block title %}
Update Lecture
{% endblock %}
{% block content %}

<h1>Edit Lecture</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
</form>

{% endblock %}

summersite/teachings/templates/update_video.html
{% extends 'base.html' %}
{% block title %}
Update Video
{% endblock %}
{% block content %}

<h1>Update Video</h1>
<form action="{% url 'update_video' uploadvideo.pk %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}